name: Metrics
on:
  schedule: [{cron: "0 12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: gbowsky
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_lines: yes
